org: vanessaandrade85
app: aws-python
service: put-in-sqs-from-s3
provider:
  name: aws
  runtime: python3.8
  region: us-west-1


  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: 
        - "arn:aws:sqs:us-west-1:*:*"


functions:
  small-files-csv:
    handler: handler.handler
    environment:
      urlSQS: "https://sqs.us-west-1.amazonaws.com/557635728628/small-files-csv"
    events:
      - s3:
         bucket: phase3-group3
         event: s3:ObjectCreated:*
         rules:
            - prefix: files-small/
         existing: true
  raw-json:
    handler: handler.handler
    environment:
      urlSQS: "https://sqs.us-west-1.amazonaws.com/557635728628/raw-json"
    events:
      - s3:
         bucket: phase3-group3
         event: s3:ObjectCreated:*
         rules:
            - prefix: json/
         existing: true